/**
* Timetic szervezeti backend
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* Contact: you@your-company.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package hu.bme.aut.android.timetic.network.models


import com.squareup.moshi.Json

/**
 * 
 * @param appointmentsToday 
 * @param onlineAppointmentsToday 
 * @param registeredUsers 
 */

data class ForAdminOverview (
    @Json(name = "appointmentsToday")
    val appointmentsToday: kotlin.Int? = null,
    @Json(name = "onlineAppointmentsToday")
    val onlineAppointmentsToday: kotlin.Int? = null,
    @Json(name = "registeredUsers")
    val registeredUsers: kotlin.Int? = null
)

