/**
* Timetic szervezeti backend
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* Contact: you@your-company.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package hu.bme.aut.android.timetic.network.models


import com.squareup.moshi.Json

/**
 * 
 * @param employeeName 
 * @param activityName 
 * @param appointmentDate 
 * @param isOnline 
 * @param duration 
 * @param income 
 */

data class ForAdminReportAppointment (
    @Json(name = "employeeName")
    val employeeName: kotlin.String? = null,
    @Json(name = "activityName")
    val activityName: kotlin.String? = null,
    @Json(name = "appointmentDate")
    val appointmentDate: kotlin.Double? = null,
    @Json(name = "isOnline")
    val isOnline: kotlin.Boolean? = null,
    @Json(name = "duration")
    val duration: kotlin.Double? = null,
    @Json(name = "income")
    val income: kotlin.Double? = null
)

