/**
* Timetic szervezeti backend
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* Contact: you@your-company.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package hu.bme.aut.android.timetic.network.models


import com.squareup.moshi.Json
import hu.bme.aut.android.timetic.network.models.CommonEmployee

/**
 * 
 * @param id 
 * @param name 
 * @param details 
 * @param isClientRegistered 
 * @param employees 
 */

data class ForClientOrganization (
    @Json(name = "id")
    val id: kotlin.String? = null,
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "details")
    val details: kotlin.String? = null,
    @Json(name = "isClientRegistered")
    val isClientRegistered: kotlin.Boolean? = null,
    @Json(name = "employees")
    val employees: kotlin.collections.List<CommonEmployee>? = null
)

