/**
* Timetic szervezeti backend
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* Contact: you@your-company.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package hu.bme.aut.android.timetic.network.models

import com.squareup.moshi.Json
import hu.bme.aut.android.timetic.network.models.ForEmployeeActivityForReport

/**
 * 
 * @param sumOnlineHours 
 * @param sumLocalHours 
 * @param sumOnlineIncome 
 * @param sumLocalIncome 
 * @param activities 
 */

data class ForEmployeeReport (
    @Json(name = "sumOnlineHours")
    val sumOnlineHours: kotlin.Double? = null,
    @Json(name = "sumLocalHours")
    val sumLocalHours: kotlin.Double? = null,
    @Json(name = "sumOnlineIncome")
    val sumOnlineIncome: kotlin.Double? = null,
    @Json(name = "sumLocalIncome")
    val sumLocalIncome: kotlin.Double? = null,
    @Json(name = "activities")
    val activities: kotlin.collections.List<ForEmployeeActivityForReport>? = null
)

