/**
* Timetic szervezeti backend
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* Contact: you@your-company.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package hu.bme.aut.android.timetic.network.models


import com.squareup.moshi.Json

/**
 * 
 * @param name 
 * @param sumHours 
 * @param sumIncome 
 */

data class ForEmployeeActivityForReport (
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "sumHours")
    val sumHours: kotlin.Double? = null,
    @Json(name = "sumIncome")
    val sumIncome: kotlin.Double? = null
)

