/**
* Timetic szervezeti backend
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* Contact: you@your-company.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package hu.bme.aut.android.timetic.network.models


import com.squareup.moshi.Json
import hu.bme.aut.android.timetic.network.models.CommonActivity
import hu.bme.aut.android.timetic.network.models.CommonClient

/**
 * 
 * @param activities 
 * @param clients 
 * @param places 
 */

data class ForEmployeeDataForAppointmentCreation (
    @Json(name = "activities")
    val activities: kotlin.collections.List<CommonActivity>? = null,
    @Json(name = "clients")
    val clients: kotlin.collections.List<CommonClient>? = null,
    @Json(name = "places")
    val places: kotlin.collections.List<kotlin.String>? = null
)

