/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Timetic szervezeti backend
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package hu.bme.aut.android.timetic.apis

import io.reactivex.Completable
import retrofit2.http.DELETE
import retrofit2.http.GET
import retrofit2.http.POST
import retrofit2.http.PUT

@JvmSuppressWildcards
interface AdminApi {
    /**
     * Lists the activities that are connected to the employee
     * The endpoint is owned by defaultname service owner
     */
    @GET("/admin/activities")
    fun adminActivitiesGet(): Completable
    /**
     * Cancels appointment
     * The endpoint is owned by defaultname service owner
     * @param appointmentId (required)
     */
    @DELETE("/admin/appointments/{appointmentId}")
    fun adminAppointmentsAppointmentIdDelete(
        @retrofit2.http.Path("appointmentId") appointmentId: Map<String, Any?>
    ): Completable
    /**
     * Gets the appointment with the given id
     * The endpoint is owned by defaultname service owner
     * @param appointmentId (required)
     */
    @GET("/admin/appointments/{appointmentId}")
    fun adminAppointmentsAppointmentIdGet(
        @retrofit2.http.Path("appointmentId") appointmentId: Map<String, Any?>
    ): Completable
    /**
     * Lists appointments for the employee
     * The endpoint is owned by defaultname service owner
     */
    @GET("/admin/appointments")
    fun adminAppointmentsGet(): Completable
    /**
     * Uploads a new appointment
     * The endpoint is owned by defaultname service owner
     */
    @POST("/admin/appointments")
    fun adminAppointmentsPost(): Completable
    /**
     * Modifies appointment
     * The endpoint is owned by defaultname service owner
     */
    @PUT("/admin/appointments")
    fun adminAppointmentsPut(): Completable
    /**
     * Lists the clients who are registered to the organization
     * The endpoint is owned by defaultname service owner
     */
    @GET("/admin/clients")
    fun adminClientsGet(): Completable
    /**
     * Registers a client
     * The endpoint is owned by defaultname service owner
     */
    @POST("/admin/clients")
    fun adminClientsPost(): Completable
    /**
     * Asks for new password
     * The endpoint is owned by defaultname service owner
     */
    @GET("/admin/forgottenPassword")
    fun adminForgottenPasswordGet(): Completable
    /**
     * Logs employee into the system
     * The endpoint is owned by defaultname service owner
     */
    @POST("/admin/login")
    fun adminLoginPost(): Completable
    /**
     * Logs employee out of the system
     * The endpoint is owned by defaultname service owner
     */
    @GET("/admin/logout")
    fun adminLogoutGet(): Completable
    /**
     * Loads data for organization details page
     * The endpoint is owned by defaultname service owner
     */
    @GET("/admin/organization")
    fun adminOrganizationGet(): Completable
    /**
     * Loads data for overview page
     * The endpoint is owned by defaultname service owner
     */
    @GET("/admin/overview")
    fun adminOverviewGet(): Completable
    /**
     * Creates a report of the work of the given period
     * The endpoint is owned by defaultname service owner
     */
    @GET("/admin/report")
    fun adminReportGet(): Completable
    /**
     * Loads admin page
     * The endpoint is owned by defaultname service owner
     */
    @GET("/")
    fun rootGet(): Completable
}
