/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Timetic szervezeti backend
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package hu.bme.aut.android.timetic.apis

import io.reactivex.Completable
import retrofit2.http.DELETE
import retrofit2.http.GET
import retrofit2.http.POST

@JvmSuppressWildcards
interface ClientApi {
    /**
     * Cancel appointment
     * The endpoint is owned by defaultname service owner
     * @param appointmentId (required)
     */
    @DELETE("/client/appointments/{appointmentId}")
    fun clientAppointmentsAppointmentIdDelete(
        @retrofit2.http.Path("appointmentId") appointmentId: Map<String, Any?>
    ): Completable
    /**
     * Lists the appointments
     * The endpoint is owned by defaultname service owner
     */
    @GET("/client/appointments")
    fun clientAppointmentsGet(): Completable
    /**
     * Logs client into the system
     * The endpoint is owned by defaultname service owner
     */
    @GET("/client/login")
    fun clientLoginGet(): Completable
    /**
     * Lists details of the organization // no authentication required
     * The endpoint is owned by defaultname service owner
     */
    @GET("/client/organization")
    fun clientOrganizationGet(): Completable
    /**
     * Refresh client's token
     * The endpoint is owned by defaultname service owner
     */
    @GET("/client/refresh")
    fun clientRefreshGet(): Completable
    /**
     * Registers client // needs to fill the form with personal info
     * The endpoint is owned by defaultname service owner
     */
    @POST("/client/register")
    fun clientRegisterPost(): Completable
    /**
     * Share their personal/client data with the organization //client is registered by employee
     * The endpoint is owned by defaultname service owner
     */
    @GET("/client/shareDataWithOrganization")
    fun clientShareDataWithOrganizationGet(): Completable
}
