/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Timetic szervezeti backend
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package hu.bme.aut.android.timetic.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property id
 * @property name
 * @property phone
 * @property email
 * @property activities
 */
@JsonClass(generateAdapter = true)
data class CommonEmployee(
    @Json(name = "id") @field:Json(name = "id") var id: String? = null,
    @Json(name = "name") @field:Json(name = "name") var name: String? = null,
    @Json(name = "phone") @field:Json(name = "phone") var phone: String? = null,
    @Json(name = "email") @field:Json(name = "email") var email: String? = null,
    @Json(name = "activities") @field:Json(name = "activities") var activities: List<CommonActivity>? = null
)
