/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Timetic szervezeti backend
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package hu.bme.aut.android.timetic.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property id
 * @property name
 * @property details
 * @property canClientContactEmployees
 * @property employees
 * @property clients
 * @property activities
 * @property addresses
 * @property clientPersonalInfoFields
 */
@JsonClass(generateAdapter = true)
data class ForAdminOrganization(
    @Json(name = "id") @field:Json(name = "id") var id: String? = null,
    @Json(name = "name") @field:Json(name = "name") var name: String? = null,
    @Json(name = "details") @field:Json(name = "details") var details: String? = null,
    @Json(name = "canClientContactEmployees") @field:Json(name = "canClientContactEmployees") var canClientContactEmployees: Boolean? = null,
    @Json(name = "employees") @field:Json(name = "employees") var employees: List<CommonEmployee>? = null,
    @Json(name = "clients") @field:Json(name = "clients") var clients: List<CommonClient>? = null,
    @Json(name = "activities") @field:Json(name = "activities") var activities: List<CommonActivity>? = null,
    @Json(name = "addresses") @field:Json(name = "addresses") var addresses: List<String>? = null,
    @Json(name = "clientPersonalInfoFields") @field:Json(name = "clientPersonalInfoFields") var clientPersonalInfoFields: List<String>? = null
)
