/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Timetic szervezeti backend
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package hu.bme.aut.android.timetic.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property appointmentsToday
 * @property onlineAppointmentsToday
 * @property registeredUsers
 */
@JsonClass(generateAdapter = true)
data class ForAdminOverview(
    @Json(name = "appointmentsToday") @field:Json(name = "appointmentsToday") var appointmentsToday: Int? = null,
    @Json(name = "onlineAppointmentsToday") @field:Json(name = "onlineAppointmentsToday") var onlineAppointmentsToday: Int? = null,
    @Json(name = "registeredUsers") @field:Json(name = "registeredUsers") var registeredUsers: Int? = null
)
