/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Timetic szervezeti backend
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package hu.bme.aut.android.timetic.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property employeeName
 * @property activityName
 * @property appointmentDate
 * @property isOnline
 * @property duration
 * @property income
 */
@JsonClass(generateAdapter = true)
data class ForAdminReportAppointment(
    @Json(name = "employeeName") @field:Json(name = "employeeName") var employeeName: String? = null,
    @Json(name = "activityName") @field:Json(name = "activityName") var activityName: String? = null,
    @Json(name = "appointmentDate") @field:Json(name = "appointmentDate") var appointmentDate: Double? = null,
    @Json(name = "isOnline") @field:Json(name = "isOnline") var isOnline: Boolean? = null,
    @Json(name = "duration") @field:Json(name = "duration") var duration: Double? = null,
    @Json(name = "income") @field:Json(name = "income") var income: Double? = null
)
