/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Timetic szervezeti backend
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package hu.bme.aut.android.timetic.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property organizationName
 * @property startDate
 * @property endDate
 * @property appointments
 */
@JsonClass(generateAdapter = true)
data class ForAdminReport(
    @Json(name = "organizationName") @field:Json(name = "organizationName") var organizationName: String? = null,
    @Json(name = "startDate") @field:Json(name = "startDate") var startDate: Double? = null,
    @Json(name = "endDate") @field:Json(name = "endDate") var endDate: Double? = null,
    @Json(name = "appointments") @field:Json(name = "appointments") var appointments: List<ForAdminReportAppointment>? = null
)
