/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Timetic szervezeti backend
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package hu.bme.aut.android.timetic.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property id
 * @property name
 * @property details
 * @property isClientRegistered
 * @property employees
 */
@JsonClass(generateAdapter = true)
data class ForClientOrganization(
    @Json(name = "id") @field:Json(name = "id") var id: String? = null,
    @Json(name = "name") @field:Json(name = "name") var name: String? = null,
    @Json(name = "details") @field:Json(name = "details") var details: String? = null,
    @Json(name = "isClientRegistered") @field:Json(name = "isClientRegistered") var isClientRegistered: Boolean? = null,
    @Json(name = "employees") @field:Json(name = "employees") var employees: List<CommonEmployee>? = null
)
