/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Timetic szervezeti backend
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package hu.bme.aut.android.timetic.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property id
 * @property clientPersonalInfoFields
 */
@JsonClass(generateAdapter = true)
data class ForEmployeeOrganization(
    @Json(name = "id") @field:Json(name = "id") var id: String? = null,
    @Json(name = "clientPersonalInfoFields") @field:Json(name = "clientPersonalInfoFields") var clientPersonalInfoFields: List<String>? = null
)
